services:
  postgres:
    image: postgres:15
    container_name: taskdb
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TaskDB
    ports:
      - "5433:5432"  # host:container (container stays 5432)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d TaskDB -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  dbgate:
    image: dbgate/dbgate:latest
    ports:
      - "3000:3000"
    networks:
    - shared_network
    depends_on:
        postgres:
          condition: service_healthy

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notesService
    ports:
      - "8002:8002"
    volumes:
    - ../task-management-logs:/app/logs
    environment:
      # Logging
      LOGGING_FILE_NAME: /app/logs/app.log

      # Containers talk to the postgres *service name* on its container port 5432
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/TaskDB
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password

    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shared_network
    restart: always

volumes:
  postgres_data:

networks:
  shared_network:
      external: true