name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  sonarcloud:
    uses: genzitizens/ci-templates/.github/workflows/sonarcloud.yml@main
    with:
      projectBaseDir: "." # optional if using default
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  push-ghcr:
    needs: sonarcloud
    uses: genzitizens/ci-templates/.github/workflows/springboot-push-to-ghcr.yml@main
    with:
      image_name: task-management
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      GHCR_ORG: ${{ secrets.GHCR_ORG }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  sync-compose:
    needs: sonarcloud
    uses: genzitizens/ci-templates/.github/workflows/sync-compose-to-vps.yml@main
    with:
      compose-path: infra/docker/docker-compose.yml
      remote-path: "/home/exeltan/task-management/docker-compose.yml"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}

  deploy:
    needs: [ push-ghcr , sync-compose ]
    uses: genzitizens/ci-templates/.github/workflows/deploy-to-vps.yml@main
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      GHCR_ORG: ${{ secrets.GHCR_ORG }}
    with:
      IMAGE_NAME: "task-management"
      COMPOSE_PATH: "/home/exeltan/task-management/docker-compose.yml"
      RUN_COMPOSE_PULL: true
